# Generated by Django 4.1.3 on 2022-11-23 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssrData', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='postLikes',
            fields=[
                ('macAddress', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('projectId', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='teamDetails',
            fields=[
                ('rollNo', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('projectId', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='youtubeLink',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='mentor',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
