# Generated by Django 4.1.3 on 2022-11-24 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssrData', '0002_postlikes_teamdetails_project_youtubelink_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teamdetails',
            old_name='rollNo',
            new_name='roll',
        ),
    ]
